
- name: Create Backend Directory
  file:
    path: ~/backend-app
    state: directory
# - name: Create Backend Directory
#   file:
#     path: /home/ubuntu/backend
#     state: directory

# - copy:
#     src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
#     dest: /home/ubuntu/backend

- copy:
    src: ~/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: ~/backend-app

# - name: Extract artifact.tar.gz to EC2 
#   unarchive:
#     src: artifact.tar.gz
#     dest: /home/ubuntu/backend
- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

# - name: "Installing Node Dependencies"
#   shell: |
#     cd /home/ubuntu/backend
#     npm i

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

# - name: Start the app
#   shell: |
#     cd /home/ubuntu/backend
#     pwd
#     sudo pm2 stop default
#     sudo pm2 start -f /home/ubuntu/backend/dist/main.js
- name: Start the app
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

# - name: Verify backend deployment
#   shell: |
#     curl localhost:3030/api/status

# - name: Enable pm2
#   become: true
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"

- name: Enable pm2
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu